import { connectDatabase, disconnectDatabase } from '../config';
import { User, Tenant, Attraction, Category, Destination, Review, Booking } from '../models';

// Import mock data structures
const categories = [
  { slug: 'museums', name: 'Museums & Galleries', icon: 'Building2', description: 'Explore world-class museums and art galleries', sortOrder: 1 },
  { slug: 'theme-parks', name: 'Theme Parks', icon: 'Ferris-wheel', description: 'Experience thrilling rides and family entertainment', sortOrder: 2 },
  { slug: 'tours', name: 'City Tours', icon: 'Map', description: 'Discover cities with guided tours and experiences', sortOrder: 3 },
  { slug: 'shows', name: 'Shows & Events', icon: 'Ticket', description: 'Enjoy live shows, concerts, and special events', sortOrder: 4 },
  { slug: 'adventures', name: 'Adventures', icon: 'Mountain', description: 'Thrilling outdoor activities and extreme sports', sortOrder: 5 },
  { slug: 'food', name: 'Food & Drink', icon: 'Utensils', description: 'Culinary experiences and food tours', sortOrder: 6 },
  { slug: 'day-trips', name: 'Day Trips', icon: 'Compass', description: 'Full-day excursions to nearby destinations', sortOrder: 7 },
  { slug: 'landmarks', name: 'Landmarks', icon: 'Landmark', description: 'Visit iconic monuments and historical sites', sortOrder: 8 },
  { slug: 'water-activities', name: 'Water Activities', icon: 'Waves', description: 'Cruises, water sports, and aquatic adventures', sortOrder: 9 },
  { slug: 'transfers', name: 'Transfers', icon: 'Car', description: 'Airport transfers and transportation services', sortOrder: 10 },
];

const destinations = [
  // Egypt Destinations
  {
    slug: 'hurghada',
    name: 'Hurghada',
    country: 'Egypt',
    continent: 'Africa',
    description: 'Hurghada is a premier Red Sea resort destination known for its pristine beaches, world-class diving, and water sports.',
    shortDescription: 'Red Sea paradise for diving and water sports',
    images: ['https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80'],
    heroImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1920&q=80',
    highlights: ['Coral Reefs', 'Snorkeling', 'Desert Safaris', 'Nightlife'],
    bestTimeToVisit: 'October to April',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 27.2574, lng: 33.8129 },
    tags: ['beach', 'water-sports', 'diving', 'resort'],
    sortOrder: 1,
  },
  {
    slug: 'sharm-el-sheikh',
    name: 'Sharm El Sheikh',
    country: 'Egypt',
    continent: 'Africa',
    description: 'Located at the tip of the Sinai Peninsula, Sharm El Sheikh offers stunning Red Sea views and world-renowned diving spots.',
    shortDescription: 'Luxurious Red Sea resort at the Sinai Peninsula',
    images: ['https://images.unsplash.com/photo-1551884170-4f149c91e9fa?w=1200&q=80'],
    heroImage: 'https://images.unsplash.com/photo-1551884170-4f149c91e9fa?w=1920&q=80',
    highlights: ['Diving', 'Snorkeling', 'Naama Bay', 'Restaurants & Bars'],
    bestTimeToVisit: 'October to April',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 27.7369, lng: 34.3394 },
    tags: ['beach', 'luxury', 'diving', 'water-sports'],
    sortOrder: 2,
  },
  {
    slug: 'cairo',
    name: 'Cairo',
    country: 'Egypt',
    continent: 'Africa',
    description: 'Cairo, the capital of Egypt, is home to the iconic Pyramids of Giza, the Egyptian Museum, and vibrant Islamic architecture.',
    shortDescription: 'Home to the Pyramids of Giza and ancient wonders',
    images: ['https://images.unsplash.com/photo-1569163139394-de4798aa62b4?w=1200&q=80'],
    heroImage: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b4?w=1920&q=80',
    highlights: ['Pyramids of Giza', 'Sphinx', 'Egyptian Museum', 'Khan el-Khalili'],
    bestTimeToVisit: 'October to April',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 30.0444, lng: 31.2357 },
    tags: ['historical', 'ancient', 'monuments', 'culture'],
    sortOrder: 3,
  },
  {
    slug: 'luxor',
    name: 'Luxor',
    country: 'Egypt',
    continent: 'Africa',
    description: 'Home to ancient Thebes and one of the world\'s greatest open-air museums, Luxor features the Valley of the Kings and stunning temples.',
    shortDescription: 'Ancient Egypt\'s most impressive historical site',
    images: ['https://images.unsplash.com/photo-1563930234-c58e88bef97f?w=1200&q=80'],
    heroImage: 'https://images.unsplash.com/photo-1563930234-c58e88bef97f?w=1920&q=80',
    highlights: ['Valley of the Kings', 'Karnak Temple', 'Luxor Temple', 'Nile Cruises'],
    bestTimeToVisit: 'October to April',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 25.6871, lng: 32.6346 },
    tags: ['historical', 'ancient', 'temples', 'cultural'],
    sortOrder: 4,
  },
  {
    slug: 'aswan',
    name: 'Aswan',
    country: 'Egypt',
    continent: 'Africa',
    description: 'Aswan is a picturesque city on the Nile River, known for the Aswan Dam, Abu Simbel temples, and Nubian culture.',
    shortDescription: 'Gateway to Nubia and Abu Simbel temples',
    images: ['https://images.unsplash.com/photo-1604631868676-d6875e99f47f?w=1200&q=80'],
    heroImage: 'https://images.unsplash.com/photo-1604631868676-d6875e99f47f?w=1920&q=80',
    highlights: ['Abu Simbel', 'Aswan Dam', 'Nile Felucca', 'Nubian Villages'],
    bestTimeToVisit: 'October to April',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 24.0889, lng: 32.8872 },
    tags: ['cultural', 'temples', 'nile', 'adventure'],
    sortOrder: 5,
  },
  {
    slug: 'dahab',
    name: 'Dahab',
    country: 'Egypt',
    continent: 'Africa',
    description: 'A laid-back Bedouin village turned resort destination, Dahab offers exceptional diving and snorkeling along the Red Sea.',
    shortDescription: 'Bohemian beach town with exceptional diving',
    images: ['https://images.unsplash.com/photo-1517576443991-9c6b7c3e68b9?w=1200&q=80'],
    heroImage: 'https://images.unsplash.com/photo-1517576443991-9c6b7c3e68b9?w=1920&q=80',
    highlights: ['Diving', 'Blue Hole', 'Canyon Dive', 'Relaxed Atmosphere'],
    bestTimeToVisit: 'October to April',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 28.5083, lng: 34.5080 },
    tags: ['beach', 'diving', 'water-sports', 'relaxation'],
    sortOrder: 6,
  },
  {
    slug: 'el-gouna',
    name: 'El Gouna',
    country: 'Egypt',
    continent: 'Africa',
    description: 'A modern, purpose-built resort town between Hurghada and the Red Sea, El Gouna offers luxury accommodations and water sports.',
    shortDescription: 'Modern luxury resort destination in the Red Sea',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80'],
    heroImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1920&q=80',
    highlights: ['Luxury Resorts', 'Golf Course', 'Marina', 'Windsurfing'],
    bestTimeToVisit: 'October to April',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 27.3600, lng: 33.7300 },
    tags: ['luxury', 'beach', 'resort', 'water-sports'],
    sortOrder: 7,
  },
  {
    slug: 'makadi-bay',
    name: 'Makadi Bay',
    country: 'Egypt',
    continent: 'Africa',
    description: 'An exclusive gated community along the Red Sea, Makadi Bay is known for its pristine beaches and high-end resorts.',
    shortDescription: 'Exclusive beachfront resort community',
    images: ['https://images.unsplash.com/photo-1514282401047-430e6570acda?w=1200&q=80'],
    heroImage: 'https://images.unsplash.com/photo-1514282401047-430e6570acda?w=1920&q=80',
    highlights: ['Private Beaches', 'Luxury Resorts', 'Marina', 'Aqua Park'],
    bestTimeToVisit: 'October to April',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 27.1333, lng: 33.6833 },
    tags: ['luxury', 'beach', 'exclusive', 'resort'],
    sortOrder: 8,
  },
  {
    slug: 'marsa-alam',
    name: 'Marsa Alam',
    country: 'Egypt',
    continent: 'Africa',
    description: 'A pristine diving destination on the Red Sea, Marsa Alam is known for its untouched coral reefs and marine wildlife.',
    shortDescription: 'Pristine Red Sea diving destination',
    images: ['https://images.unsplash.com/photo-1583109282925-404b7691c545?w=1200&q=80'],
    heroImage: 'https://images.unsplash.com/photo-1583109282925-404b7691c545?w=1920&q=80',
    highlights: ['Coral Reefs', 'Dolphin Encounters', 'Undiscovered Wrecks', 'Tranquility'],
    bestTimeToVisit: 'October to April',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 25.9764, lng: 34.5761 },
    tags: ['diving', 'marine-life', 'beach', 'adventure'],
    sortOrder: 9,
  },
  {
    slug: 'red-sea',
    name: 'Red Sea Region',
    country: 'Egypt',
    continent: 'Africa',
    description: 'The Red Sea region of Egypt stretches along the coast offering world-class beaches, diving, and water sports.',
    shortDescription: 'Pristine beaches and world-class water sports',
    images: ['https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80'],
    heroImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1920&q=80',
    highlights: ['Diving', 'Snorkeling', 'Water Sports', 'Beach Resorts'],
    bestTimeToVisit: 'October to April',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 27.2500, lng: 33.8000 },
    tags: ['beach', 'water-sports', 'diving', 'adventure'],
    sortOrder: 10,
  },
  {
    slug: 'soma-bay',
    name: 'Soma Bay',
    country: 'Egypt',
    continent: 'Africa',
    description: 'A serene beach destination south of Hurghada known for water sports and relaxation along the Red Sea.',
    shortDescription: 'Peaceful Red Sea beach escape',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80'],
    heroImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1920&q=80',
    highlights: ['Windsurfing', 'Kitesurfing', 'Snorkeling', 'Peaceful Beaches'],
    bestTimeToVisit: 'October to April',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 26.8000, lng: 33.9500 },
    tags: ['beach', 'water-sports', 'windsurfing', 'relaxation'],
    sortOrder: 11,
  },
  {
    slug: 'taba',
    name: 'Taba',
    country: 'Egypt',
    continent: 'Africa',
    description: 'Located at the northernmost tip of the Red Sea where Egypt meets Israel, Taba offers dramatic coastal scenery and diving.',
    shortDescription: 'Dramatic mountain scenery and Red Sea diving',
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80'],
    heroImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&q=80',
    highlights: ['Mountain Scenery', 'Diving', 'Desert Hikes', 'Peaceful Setting'],
    bestTimeToVisit: 'October to April',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 29.5830, lng: 34.7686 },
    tags: ['diving', 'adventure', 'mountain', 'scenic'],
    sortOrder: 12,
  },
  {
    slug: 'egypt',
    name: 'Egypt',
    country: 'Egypt',
    continent: 'Africa',
    description: 'Egypt is a country of ancient wonders, from the Pyramids of Giza to the temples of Luxor, combined with modern beach resorts.',
    shortDescription: 'Land of ancient wonders and modern resorts',
    images: ['https://images.unsplash.com/photo-1569163139394-de4798aa62b4?w=1200&q=80'],
    heroImage: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b4?w=1920&q=80',
    highlights: ['Pyramids', 'Temples', 'Nile River', 'Red Sea Beaches'],
    bestTimeToVisit: 'October to April',
    timezone: 'Africa/Cairo',
    coordinates: { lat: 26.8206, lng: 30.8025 },
    tags: ['historical', 'cultural', 'adventure', 'beaches'],
    sortOrder: 13,
  },
];

const attractions = [
  // Egypt Attractions
  {
    slug: 'cairo-night-cruise',
    title: 'Cairo Night Cruise on the Nile',
    shortDescription: 'Magical evening Nile cruise with dinner and entertainment in Cairo',
    description: 'Experience the romance of the Nile River with an elegant night cruise featuring traditional dinner and live entertainment.',
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
    ],
    category: 'water-activities',
    subcategory: 'cruises',
    destination: { city: 'Cairo', country: 'Egypt', coordinates: { lat: 30.0444, lng: 31.2357 } },
    duration: '3 hours',
    languages: ['English', 'Arabic', 'French', 'German'],
    rating: 4.7,
    reviewCount: 234,
    priceFrom: 45,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Standard Cruise', description: 'Dinner and entertainment included', price: 45 },
      { id: 'opt_2', name: 'VIP Cruise', description: 'Premium seating and beverages', price: 75 },
    ],
    highlights: ['Nile River views', 'Traditional dinner', 'Live entertainment', 'Belly dance show'],
    inclusions: ['Cruise ticket', 'Dinner buffet', 'Live show', 'Soft beverages'],
    exclusions: ['Hotel pickup', 'Alcoholic drinks'],
    meetingPoint: { address: '2 Saray El Gezira St, Zamalek, Cairo', instructions: 'Meet at cruise terminal', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 24 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 30 },
    seo: { metaTitle: 'Cairo Night Nile Cruise', metaDescription: 'Book Nile dinner cruise in Cairo' },
    status: 'active',
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'cairo-tour-from-hurghada',
    title: 'Cairo Day Tour from Hurghada',
    shortDescription: 'Full-day Cairo excursion from Hurghada including Pyramids and Museum',
    description: 'Fly from Hurghada to Cairo for an unforgettable day visiting the Pyramids of Giza and exploring ancient Egyptian history.',
    images: [
      'https://images.unsplash.com/photo-1569163139394-de4798aa62b4?w=1200&q=80',
      'https://images.unsplash.com/photo-1503781333405-ea56b76a4f9e?w=1200&q=80',
    ],
    category: 'day-trips',
    subcategory: 'tours',
    destination: { city: 'Cairo', country: 'Egypt', coordinates: { lat: 30.0444, lng: 31.2357 } },
    duration: 'Full day (12 hours)',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.8,
    reviewCount: 312,
    priceFrom: 65,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Basic Tour', description: 'Flight and guided tour', price: 65 },
      { id: 'opt_2', name: 'Premium Tour', description: 'Flight, tour, and lunch included', price: 95 },
    ],
    highlights: ['Pyramids of Giza', 'Sphinx', 'Egyptian Museum', 'Pharaonic lunch'],
    inclusions: ['Flight from Hurghada', 'Professional guide', 'Entrance fees'],
    exclusions: ['Lunch', 'Travel insurance'],
    meetingPoint: { address: 'Hurghada International Airport', instructions: 'Meet at airport 2 hours before flight', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 7 days before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 14 },
    seo: { metaTitle: 'Cairo Day Tour from Hurghada', metaDescription: 'Book Cairo tour from Hurghada' },
    status: 'active',
    featured: true,
    sortOrder: 2,
  },
  {
    slug: 'cairo-tours-packages',
    title: 'Cairo Tours Packages',
    shortDescription: 'Customizable multi-day Cairo tour packages with hotels and guides',
    description: 'Comprehensive Cairo tour packages combining major historical sites with comfortable accommodations.',
    images: [
      'https://images.unsplash.com/photo-1551632440-9e3c5e4ee775?w=1200&q=80',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    ],
    category: 'tours',
    subcategory: 'packages',
    destination: { city: 'Cairo', country: 'Egypt', coordinates: { lat: 30.0444, lng: 31.2357 } },
    duration: '3-5 days',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.6,
    reviewCount: 178,
    priceFrom: 85,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: '3-Day Package', description: 'Hotel + guides + meals', price: 85 },
      { id: 'opt_2', name: '5-Day Package', description: 'Cairo + Alexandria + Luxor', price: 150 },
    ],
    highlights: ['Pyramids', 'Museums', 'Temples', 'Guided tours'],
    inclusions: ['Accommodation', 'Daily breakfast', 'Professional guide', 'Entrance fees'],
    exclusions: ['Flights', 'Travel insurance'],
    meetingPoint: { address: 'Cairo downtown', instructions: 'Hotel pickup available', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 10 days before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'free-cancellation'],
    availability: { type: 'date-only', advanceBooking: 21 },
    seo: { metaTitle: 'Cairo Tours Packages', metaDescription: 'Book Cairo tour packages' },
    status: 'active',
    featured: true,
    sortOrder: 3,
  },
  {
    slug: 'camel-riding-hurghada',
    title: 'Camel Riding in Hurghada Desert',
    shortDescription: 'Thrilling camel riding adventure through the Egyptian desert',
    description: 'Experience the magic of the Hurghada desert on the back of a camel, enjoying sunset and traditional Bedouin hospitality.',
    images: [
      'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=1200&q=80',
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=80',
    ],
    category: 'adventures',
    subcategory: 'animal-experiences',
    destination: { city: 'Hurghada', country: 'Egypt', coordinates: { lat: 27.2574, lng: 33.8129 } },
    duration: '2-3 hours',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.5,
    reviewCount: 156,
    priceFrom: 25,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Adult Ride', description: '2-3 hours camel riding', price: 25 },
      { id: 'opt_2', name: 'Child Ride', description: 'Age 4-12', price: 15 },
    ],
    highlights: ['Desert landscape', 'Sunset views', 'Camel experience', 'Bedouin village'],
    inclusions: ['Camel riding', 'Bedouin tea', 'Hotel pickup'],
    exclusions: ['Photos', 'Meals'],
    meetingPoint: { address: 'Hurghada beachfront', instructions: 'Hotel pickup available', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 6 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'free-cancellation'],
    availability: { type: 'date-only', advanceBooking: 7 },
    seo: { metaTitle: 'Camel Riding in Hurghada', metaDescription: 'Book camel riding tour in Hurghada' },
    status: 'active',
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'giftun-island-hurghada',
    title: 'Giftun Island Snorkeling Trip',
    shortDescription: 'Full-day snorkeling adventure to pristine Giftun Island',
    description: 'Explore vibrant coral reefs and tropical fish at Giftun Island, one of Hurghada\'s most beautiful snorkeling destinations.',
    images: [
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80',
      'https://images.unsplash.com/photo-1583109282925-404b7691c545?w=1200&q=80',
    ],
    category: 'water-activities',
    subcategory: 'snorkeling',
    destination: { city: 'Hurghada', country: 'Egypt', coordinates: { lat: 27.2574, lng: 33.8129 } },
    duration: 'Full day (8 hours)',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.8,
    reviewCount: 287,
    priceFrom: 30,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Standard Snorkeling', description: 'Boat, snorkel gear, lunch', price: 30 },
      { id: 'opt_2', name: 'Luxury Snorkeling', description: 'Premium boat and buffet lunch', price: 50 },
    ],
    highlights: ['Coral reefs', 'Tropical fish', 'Pristine island', 'Beach time'],
    inclusions: ['Boat trip', 'Snorkel gear', 'Lunch and drinks', 'Guide'],
    exclusions: ['Photos', 'Underwater camera rental'],
    meetingPoint: { address: 'Hurghada Marina', instructions: 'Meet at marina office', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 24 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 7 },
    seo: { metaTitle: 'Giftun Island Snorkeling', metaDescription: 'Book Giftun Island snorkeling trip' },
    status: 'active',
    featured: true,
    sortOrder: 2,
  },
  {
    slug: 'horse-riding-hurghada',
    title: 'Horse Riding on Hurghada Beach',
    shortDescription: 'Scenic horseback riding along Hurghada\'s beautiful Red Sea beaches',
    description: 'Ride along pristine beaches with views of the Red Sea and desert landscape.',
    images: [
      'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=1200&q=80',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    ],
    category: 'adventures',
    subcategory: 'animal-experiences',
    destination: { city: 'Hurghada', country: 'Egypt', coordinates: { lat: 27.2574, lng: 33.8129 } },
    duration: '2 hours',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.6,
    reviewCount: 124,
    priceFrom: 20,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Beach Ride', description: '2-hour beach ride', price: 20 },
      { id: 'opt_2', name: 'Extended Ride', description: '3-hour ride with refreshments', price: 30 },
    ],
    highlights: ['Beach riding', 'Red Sea views', 'Desert scenery', 'Sunset option'],
    inclusions: ['Horse rental', 'Guide', 'Hotel pickup'],
    exclusions: ['Photos', 'Meals'],
    meetingPoint: { address: 'Hurghada beachfront', instructions: 'Meeting point by the beach', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 4 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 3 },
    seo: { metaTitle: 'Horse Riding Hurghada', metaDescription: 'Book horse riding in Hurghada' },
    status: 'active',
    featured: true,
    sortOrder: 3,
  },
  {
    slug: 'hurghada-fishing',
    title: 'Hurghada Deep Sea Fishing',
    shortDescription: 'Exciting deep-sea fishing expedition in the Red Sea',
    description: 'Experience thrilling deep-sea fishing in the pristine waters of the Red Sea with professional anglers.',
    images: [
      'https://images.unsplash.com/photo-1489749798305-4fea3ba63d60?w=1200&q=80',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=80',
    ],
    category: 'adventures',
    subcategory: 'fishing',
    destination: { city: 'Hurghada', country: 'Egypt', coordinates: { lat: 27.2574, lng: 33.8129 } },
    duration: '6-8 hours',
    languages: ['English', 'Arabic', 'German'],
    rating: 4.7,
    reviewCount: 89,
    priceFrom: 55,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Group Fishing', description: 'Shared boat, all-day fishing', price: 55 },
      { id: 'opt_2', name: 'Private Fishing', description: 'Private boat rental', price: 120 },
    ],
    highlights: ['Deep-sea fishing', 'Professional guides', 'Equipment provided', 'Barbecue lunch'],
    inclusions: ['Boat', 'Fishing equipment', 'Lunch and drinks', 'Guide'],
    exclusions: ['Fish cleaning', 'Photos'],
    meetingPoint: { address: 'Hurghada Marina', instructions: 'Meet at fishing charter dock', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 24 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 7 },
    seo: { metaTitle: 'Deep Sea Fishing Hurghada', metaDescription: 'Book deep sea fishing in Hurghada' },
    status: 'active',
    featured: true,
    sortOrder: 4,
  },
  {
    slug: 'hurghada-jeep-safari',
    title: 'Hurghada Jeep Desert Safari',
    shortDescription: 'Thrilling off-road jeep adventure through the Hurghada desert',
    description: 'Drive through the scenic desert landscape in a 4x4 jeep with stops at Bedouin villages and desert viewpoints.',
    images: [
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&q=80',
      'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=1200&q=80',
    ],
    category: 'adventures',
    subcategory: 'safari',
    destination: { city: 'Hurghada', country: 'Egypt', coordinates: { lat: 27.2574, lng: 33.8129 } },
    duration: '4-5 hours',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.7,
    reviewCount: 198,
    priceFrom: 35,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Standard Safari', description: 'Jeep safari with guide and tea', price: 35 },
      { id: 'opt_2', name: 'Sunset Safari', description: 'Evening safari with dinner', price: 55 },
    ],
    highlights: ['Off-road driving', 'Desert landscape', 'Bedouin villages', 'Sunset views'],
    inclusions: ['Jeep rental', 'Driver', 'Bedouin tea', 'Hotel pickup'],
    exclusions: ['Meals', 'Photos'],
    meetingPoint: { address: 'Hurghada hotel area', instructions: 'Hotel pickup available', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 6 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 3 },
    seo: { metaTitle: 'Jeep Desert Safari Hurghada', metaDescription: 'Book jeep safari in Hurghada' },
    status: 'active',
    featured: true,
    sortOrder: 5,
  },
  {
    slug: 'hurghada-luxury-cruise',
    title: 'Hurghada Luxury Yacht Cruise',
    shortDescription: 'Premium yacht cruise with snorkeling and beachfront dining',
    description: 'Enjoy an exclusive luxury yacht experience with snorkeling stops and gourmet dining on the Red Sea.',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
    ],
    category: 'water-activities',
    subcategory: 'cruises',
    destination: { city: 'Hurghada', country: 'Egypt', coordinates: { lat: 27.2574, lng: 33.8129 } },
    duration: 'Full day (8 hours)',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.9,
    reviewCount: 156,
    priceFrom: 75,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Yacht Cruise', description: 'Full day yacht with snorkel and lunch', price: 75 },
      { id: 'opt_2', name: 'Premium Yacht', description: 'Luxury yacht with premium dining', price: 120 },
    ],
    highlights: ['Luxury yacht', 'Snorkeling stops', 'Gourmet lunch', 'Sunset views'],
    inclusions: ['Yacht charter', 'Snorkel gear', 'Lunch and drinks', 'Guide'],
    exclusions: ['Photos', 'Underwater camera'],
    meetingPoint: { address: 'Hurghada Marina', instructions: 'Meet at luxury yacht dock', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 48 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 7 },
    seo: { metaTitle: 'Luxury Yacht Cruise Hurghada', metaDescription: 'Book luxury yacht in Hurghada' },
    status: 'active',
    featured: true,
    sortOrder: 6,
  },
  {
    slug: 'hurghada-private-safari',
    title: 'Hurghada Private Desert Safari',
    shortDescription: 'Exclusive private desert safari with personalized experience',
    description: 'Experience a customized private desert safari with your own jeep, driver, and personalized itinerary.',
    images: [
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&q=80',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    ],
    category: 'adventures',
    subcategory: 'safari',
    destination: { city: 'Hurghada', country: 'Egypt', coordinates: { lat: 27.2574, lng: 33.8129 } },
    duration: '5-6 hours',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.8,
    reviewCount: 142,
    priceFrom: 60,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Private Safari', description: 'Private jeep for up to 4 people', price: 60 },
      { id: 'opt_2', name: 'Family Safari', description: 'Private jeep with activities', price: 90 },
    ],
    highlights: ['Private jeep', 'Personalized route', 'Bedouin hospitality', 'Sunset experience'],
    inclusions: ['Private jeep', 'Professional guide', 'Bedouin tea', 'Hotel pickup'],
    exclusions: ['Meals', 'Photos'],
    meetingPoint: { address: 'Your hotel', instructions: 'Hotel pickup included', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 24 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 5 },
    seo: { metaTitle: 'Private Desert Safari Hurghada', metaDescription: 'Book private safari in Hurghada' },
    status: 'active',
    featured: true,
    sortOrder: 7,
  },
  {
    slug: 'hurghada-private-tours',
    title: 'Hurghada Private City Tour',
    shortDescription: 'Personalized city tour of Hurghada with local insights',
    description: 'Discover Hurghada\'s attractions with a private guide including downtown, beaches, and local markets.',
    images: [
      'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1200&q=80',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80',
    ],
    category: 'tours',
    subcategory: 'city-tours',
    destination: { city: 'Hurghada', country: 'Egypt', coordinates: { lat: 27.2574, lng: 33.8129 } },
    duration: '4 hours',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.6,
    reviewCount: 98,
    priceFrom: 40,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Basic Tour', description: 'City highlights and markets', price: 40 },
      { id: 'opt_2', name: 'Extended Tour', description: 'Includes lunch at local restaurant', price: 60 },
    ],
    highlights: ['Downtown Hurghada', 'Local markets', 'Beach views', 'Shopping'],
    inclusions: ['Private guide', 'Hotel pickup', 'Bottled water'],
    exclusions: ['Lunch', 'Shopping'],
    meetingPoint: { address: 'Your hotel', instructions: 'Hotel pickup included', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 4 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 2 },
    seo: { metaTitle: 'Private City Tour Hurghada', metaDescription: 'Book private tour in Hurghada' },
    status: 'active',
    featured: true,
    sortOrder: 8,
  },
  {
    slug: 'hurghada-snorkeling',
    title: 'Hurghada Snorkeling Adventure',
    shortDescription: 'Full-day snorkeling trip to multiple reef locations',
    description: 'Explore multiple snorkeling sites with professional guides and all equipment provided.',
    images: [
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80',
      'https://images.unsplash.com/photo-1583109282925-404b7691c545?w=1200&q=80',
    ],
    category: 'water-activities',
    subcategory: 'snorkeling',
    destination: { city: 'Hurghada', country: 'Egypt', coordinates: { lat: 27.2574, lng: 33.8129 } },
    duration: 'Full day (8 hours)',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.7,
    reviewCount: 267,
    priceFrom: 25,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Adult Snorkeling', description: 'Full day snorkeling with lunch', price: 25 },
      { id: 'opt_2', name: 'Child Snorkeling', description: 'Age 4-12, shorter duration', price: 15 },
    ],
    highlights: ['Multiple reef sites', 'Marine life', 'Equipment included', 'Beach time'],
    inclusions: ['Boat', 'Snorkel gear', 'Lunch and drinks', 'Guide', 'Hotel pickup'],
    exclusions: ['Photos', 'Underwater camera rental'],
    meetingPoint: { address: 'Hurghada Marina', instructions: 'Meet at marina', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 24 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 3 },
    seo: { metaTitle: 'Hurghada Snorkeling Adventure', metaDescription: 'Book snorkeling in Hurghada' },
    status: 'active',
    featured: true,
    sortOrder: 9,
  },
  {
    slug: 'hurghada-spa',
    title: 'Hurghada Luxury Spa Experience',
    shortDescription: 'Relaxing spa treatments in a luxurious Hurghada resort',
    description: 'Pamper yourself with world-class spa treatments including massages, body treatments, and wellness therapies.',
    images: [
      'https://images.unsplash.com/photo-1544161515-4ab60908e72b?w=1200&q=80',
      'https://images.unsplash.com/photo-1528964266-1b0fd6e0ac5b?w=1200&q=80',
    ],
    category: 'food',
    subcategory: 'spa',
    destination: { city: 'Hurghada', country: 'Egypt', coordinates: { lat: 27.2574, lng: 33.8129 } },
    duration: '2-3 hours',
    languages: ['English', 'Arabic', 'German'],
    rating: 4.8,
    reviewCount: 176,
    priceFrom: 50,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Classic Massage', description: '60-min relaxation massage', price: 50 },
      { id: 'opt_2', name: 'Luxury Package', description: 'Multiple treatments and wellness', price: 85 },
    ],
    highlights: ['Professional therapists', 'Luxury amenities', 'Relaxation', 'Wellness treatments'],
    inclusions: ['Massage or treatment', 'Refreshments', 'Use of facilities'],
    exclusions: ['Lunch', 'Additional treatments'],
    meetingPoint: { address: 'Luxury spa resort Hurghada', instructions: 'Resort location near beach', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 12 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'time-slots', advanceBooking: 5 },
    seo: { metaTitle: 'Spa Treatments Hurghada', metaDescription: 'Book spa in Hurghada' },
    status: 'active',
    featured: true,
    sortOrder: 10,
  },
  {
    slug: 'luxor-air-balloon',
    title: 'Luxor Hot Air Balloon Ride',
    shortDescription: 'Breathtaking hot air balloon flight over Luxor temples at sunrise',
    description: 'Experience magical sunrise views of the Valley of the Kings and Luxor temples from a hot air balloon.',
    images: [
      'https://images.unsplash.com/photo-1433086720990-3a0a18bd5e97?w=1200&q=80',
      'https://images.unsplash.com/photo-1563930234-c58e88bef97f?w=1200&q=80',
    ],
    category: 'adventures',
    subcategory: 'aerial-experiences',
    destination: { city: 'Luxor', country: 'Egypt', coordinates: { lat: 25.6871, lng: 32.6346 } },
    duration: '3 hours (1-hour flight)',
    languages: ['English', 'Arabic', 'German'],
    rating: 4.9,
    reviewCount: 234,
    priceFrom: 45,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Standard Flight', description: '1-hour balloon flight', price: 45 },
      { id: 'opt_2', name: 'Premium Flight', description: 'Champagne breakfast included', price: 65 },
    ],
    highlights: ['Hot air balloon', 'Sunrise views', 'Temple views', 'Scenic photography'],
    inclusions: ['Balloon flight', 'Hotel pickup', 'Bottled water'],
    exclusions: ['Breakfast', 'Photos'],
    meetingPoint: { address: 'Luxor hotel pickup', instructions: 'Early morning pickup', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 24 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 7 },
    seo: { metaTitle: 'Hot Air Balloon Luxor', metaDescription: 'Book balloon ride in Luxor' },
    status: 'active',
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'luxor-tour-from-hurghada',
    title: 'Luxor Day Tour from Hurghada',
    shortDescription: 'Full-day tour to Luxor temples from Hurghada by flight',
    description: 'Fly to Luxor for an unforgettable day exploring Valley of the Kings, Karnak Temple, and Luxor Temple.',
    images: [
      'https://images.unsplash.com/photo-1563930234-c58e88bef97f?w=1200&q=80',
      'https://images.unsplash.com/photo-1504681869696-d977e3a6a91a?w=1200&q=80',
    ],
    category: 'day-trips',
    subcategory: 'tours',
    destination: { city: 'Luxor', country: 'Egypt', coordinates: { lat: 25.6871, lng: 32.6346 } },
    duration: 'Full day (14 hours)',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.8,
    reviewCount: 289,
    priceFrom: 55,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Basic Tour', description: 'Flight and guided tour', price: 55 },
      { id: 'opt_2', name: 'Premium Tour', description: 'Flight, tour, lunch and beverages', price: 85 },
    ],
    highlights: ['Valley of Kings', 'Karnak Temple', 'Luxor Temple', 'Hot air balloon option'],
    inclusions: ['Flight', 'Professional guide', 'Entrance fees'],
    exclusions: ['Lunch', 'Photos'],
    meetingPoint: { address: 'Hurghada Airport', instructions: 'Meet 2 hours before flight', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 7 days before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 14 },
    seo: { metaTitle: 'Luxor Day Tour from Hurghada', metaDescription: 'Book Luxor tour from Hurghada' },
    status: 'active',
    featured: true,
    sortOrder: 2,
  },
  {
    slug: 'makadi-bay-safari',
    title: 'Makadi Bay Desert Safari',
    shortDescription: 'Desert safari adventure from Makadi Bay resort',
    description: 'Off-road jeep safari through the desert with Bedouin village visits and traditional tea.',
    images: [
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200&q=80',
      'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=1200&q=80',
    ],
    category: 'adventures',
    subcategory: 'safari',
    destination: { city: 'Makadi Bay', country: 'Egypt', coordinates: { lat: 27.1333, lng: 33.6833 } },
    duration: '4-5 hours',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.6,
    reviewCount: 134,
    priceFrom: 30,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Standard Safari', description: 'Jeep safari with tea', price: 30 },
      { id: 'opt_2', name: 'Sunset Safari', description: 'Evening safari with dinner', price: 50 },
    ],
    highlights: ['Desert landscape', 'Bedouin villages', 'Off-road driving', 'Sunset views'],
    inclusions: ['Jeep rental', 'Driver/guide', 'Bedouin tea', 'Hotel pickup'],
    exclusions: ['Meals', 'Photos'],
    meetingPoint: { address: 'Makadi Bay resorts', instructions: 'Hotel pickup available', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 6 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 3 },
    seo: { metaTitle: 'Desert Safari Makadi Bay', metaDescription: 'Book safari in Makadi Bay' },
    status: 'active',
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'makadi-bay-snorkeling',
    title: 'Makadi Bay Snorkeling Trip',
    shortDescription: 'Half-day snorkeling excursion from Makadi Bay',
    description: 'Explore the beautiful coral reefs and marine life just minutes from Makadi Bay.',
    images: [
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80',
      'https://images.unsplash.com/photo-1583109282925-404b7691c545?w=1200&q=80',
    ],
    category: 'water-activities',
    subcategory: 'snorkeling',
    destination: { city: 'Makadi Bay', country: 'Egypt', coordinates: { lat: 27.1333, lng: 33.6833 } },
    duration: '4-5 hours',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.7,
    reviewCount: 189,
    priceFrom: 25,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Adult Snorkeling', description: 'Half-day trip with snacks', price: 25 },
      { id: 'opt_2', name: 'Child Snorkeling', description: 'Age 4-12', price: 15 },
    ],
    highlights: ['Coral reefs', 'Tropical fish', 'Clear water', 'Close proximity to resort'],
    inclusions: ['Boat', 'Snorkel gear', 'Snacks and drinks', 'Guide'],
    exclusions: ['Lunch', 'Photos'],
    meetingPoint: { address: 'Makadi Bay beach', instructions: 'Resort beach area', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 12 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 3 },
    seo: { metaTitle: 'Snorkeling Makadi Bay', metaDescription: 'Book snorkeling in Makadi Bay' },
    status: 'active',
    featured: true,
    sortOrder: 2,
  },
  {
    slug: 'orange-bay-tours',
    title: 'Orange Bay Island Excursion',
    shortDescription: 'Beautiful island day trip with snorkeling and beach time',
    description: 'Visit pristine Orange Bay Island with crystal-clear waters and vibrant coral reefs.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80',
    ],
    category: 'water-activities',
    subcategory: 'island-tours',
    destination: { city: 'Hurghada', country: 'Egypt', coordinates: { lat: 27.2574, lng: 33.8129 } },
    duration: 'Full day (8 hours)',
    languages: ['English', 'Arabic', 'German', 'Russian'],
    rating: 4.6,
    reviewCount: 156,
    priceFrom: 35,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Standard Island Tour', description: 'Boat, snorkel, lunch', price: 35 },
      { id: 'opt_2', name: 'VIP Island Tour', description: 'Premium amenities and buffet', price: 55 },
    ],
    highlights: ['Island beaches', 'Snorkeling', 'Clear waters', 'Scenic beauty'],
    inclusions: ['Boat transfer', 'Snorkel gear', 'Lunch and drinks', 'Guide', 'Hotel pickup'],
    exclusions: ['Photos', 'Towels'],
    meetingPoint: { address: 'Hurghada Marina', instructions: 'Meet at marina dock', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 24 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 5 },
    seo: { metaTitle: 'Orange Bay Island Tour', metaDescription: 'Book Orange Bay island trip' },
    status: 'active',
    featured: true,
    sortOrder: 2,
  },
  {
    slug: 'parasailing-hurghada',
    title: 'Parasailing in Hurghada',
    shortDescription: 'Thrilling parasailing adventure with Red Sea views',
    description: 'Soar above the Red Sea on an exciting parasailing adventure with stunning coastal views.',
    images: [
      'https://images.unsplash.com/photo-1558612166-12a8cc15cfb3?w=1200&q=80',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&q=80',
    ],
    category: 'water-activities',
    subcategory: 'water-sports',
    destination: { city: 'Hurghada', country: 'Egypt', coordinates: { lat: 27.2574, lng: 33.8129 } },
    duration: '1-2 hours',
    languages: ['English', 'Arabic', 'German'],
    rating: 4.7,
    reviewCount: 112,
    priceFrom: 40,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Single Parasail', description: 'One parasailing experience', price: 40 },
      { id: 'opt_2', name: 'Tandem Parasail', description: 'Two people together', price: 65 },
    ],
    highlights: ['Aerial views', 'Red Sea views', 'Thrilling experience', 'Professional guides'],
    inclusions: ['Parasailing equipment', 'Boat transfer', 'Life jacket', 'Guide'],
    exclusions: ['Photos', 'Video'],
    meetingPoint: { address: 'Hurghada Beach', instructions: 'Water sports center', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 4 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['instant-confirm'],
    availability: { type: 'time-slots', advanceBooking: 3 },
    seo: { metaTitle: 'Parasailing Hurghada', metaDescription: 'Book parasailing in Hurghada' },
    status: 'active',
    featured: true,
    sortOrder: 3,
  },
  {
    slug: 'pyramids-excursions',
    title: 'Pyramids of Giza Excursion',
    shortDescription: 'Guided tour of the iconic Pyramids of Giza and Sphinx',
    description: 'Explore the ancient Pyramids of Giza, one of the world\'s most iconic archaeological sites.',
    images: [
      'https://images.unsplash.com/photo-1569163139394-de4798aa62b4?w=1200&q=80',
      'https://images.unsplash.com/photo-1562520503-e6f7b0f59bb2?w=1200&q=80',
    ],
    category: 'landmarks',
    subcategory: 'monuments',
    destination: { city: 'Cairo', country: 'Egypt', coordinates: { lat: 29.9759, lng: 31.1344 } },
    duration: '4-5 hours',
    languages: ['English', 'Arabic', 'German', 'Russian', 'French'],
    rating: 4.8,
    reviewCount: 456,
    priceFrom: 70,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Giza Tour', description: 'Pyramids and Sphinx tour', price: 70 },
      { id: 'opt_2', name: 'Premium Tour', description: 'Includes Egyptian Museum', price: 110 },
    ],
    highlights: ['Great Pyramids', 'Sphinx statue', 'Ancient wonders', 'Photo opportunities'],
    inclusions: ['Professional guide', 'Entrance fees', 'Hotel pickup', 'Bottled water'],
    exclusions: ['Lunch', 'Camel riding'],
    meetingPoint: { address: 'Giza Plateau', instructions: 'Meet at main entrance', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 24 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 7 },
    seo: { metaTitle: 'Pyramids of Giza Tour', metaDescription: 'Book Pyramids excursion' },
    status: 'active',
    featured: true,
    sortOrder: 4,
  },
  {
    slug: 'sharm-dinner-cruise',
    title: 'Sharm El Sheikh Dinner Cruise',
    shortDescription: 'Evening Nile dinner cruise with entertainment in Sharm',
    description: 'Enjoy a romantic dinner cruise on the Red Sea with live entertainment and sunset views.',
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&q=80',
      'https://images.unsplash.com/photo-1551884170-4f149c91e9fa?w=1200&q=80',
    ],
    category: 'water-activities',
    subcategory: 'dinner-cruises',
    destination: { city: 'Sharm El Sheikh', country: 'Egypt', coordinates: { lat: 27.7369, lng: 34.3394 } },
    duration: '3-4 hours',
    languages: ['English', 'Arabic', 'German'],
    rating: 4.7,
    reviewCount: 267,
    priceFrom: 55,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Standard Dinner', description: 'Buffet dinner and show', price: 55 },
      { id: 'opt_2', name: 'VIP Dinner', description: 'Premium seating and beverages', price: 85 },
    ],
    highlights: ['Dinner cruise', 'Red Sea views', 'Live entertainment', 'Sunset views'],
    inclusions: ['Dinner buffet', 'Live entertainment', 'Soft beverages', 'Hotel pickup'],
    exclusions: ['Alcoholic beverages', 'Photos'],
    meetingPoint: { address: 'Naama Bay Marina, Sharm El Sheikh', instructions: 'Meet at marina', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 24 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 7 },
    seo: { metaTitle: 'Sharm Dinner Cruise', metaDescription: 'Book dinner cruise in Sharm' },
    status: 'active',
    featured: true,
    sortOrder: 1,
  },
  {
    slug: 'toureg-safari',
    title: 'Touareg Desert Safari Adventure',
    shortDescription: 'Authentic desert safari with Touareg guides and traditional experience',
    description: 'Experience a genuine desert adventure with Touareg guides, camel trekking, and Bedouin hospitality.',
    images: [
      'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=1200&q=80',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
    ],
    category: 'adventures',
    subcategory: 'cultural-experiences',
    destination: { city: 'Hurghada', country: 'Egypt', coordinates: { lat: 27.2574, lng: 33.8129 } },
    duration: '5-6 hours',
    languages: ['English', 'Arabic', 'German'],
    rating: 4.8,
    reviewCount: 198,
    priceFrom: 45,
    currency: 'EGP',
    pricingOptions: [
      { id: 'opt_1', name: 'Camel Safari', description: 'Camel trekking with guide', price: 45 },
      { id: 'opt_2', name: 'Full Experience', description: 'Camel ride with overnight camp', price: 120 },
    ],
    highlights: ['Touareg guides', 'Camel trekking', 'Desert landscape', 'Bedouin camp'],
    inclusions: ['Camel rental', 'Touareg guide', 'Bedouin tea and meals', 'Hotel pickup'],
    exclusions: ['Photos', 'Overnight accommodation fees'],
    meetingPoint: { address: 'Hurghada desert camp', instructions: 'Desert meeting point', mapUrl: 'https://maps.google.com' },
    cancellationPolicy: 'Free cancellation up to 24 hours before',
    instantConfirmation: true,
    mobileTicket: true,
    badges: ['bestseller', 'instant-confirm'],
    availability: { type: 'date-only', advanceBooking: 7 },
    seo: { metaTitle: 'Touareg Desert Safari', metaDescription: 'Book Touareg safari' },
    status: 'active',
    featured: true,
    sortOrder: 11,
  },
];

const tenants = [
  // Egypt Tenants
  {
    slug: 'hurghada-tours',
    name: 'Hurghada Tours & Excursions',
    domain: 'hurghada-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=200&h=60&fit=crop',
    tagline: 'Discover the Red Sea Paradise',
    description: 'Your gateway to the best tours and excursions in Hurghada',
    theme: { primaryColor: '#0066CC', secondaryColor: '#00CCFF', accentColor: '#FF9500' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@hurghada-tours.com', address: 'Hurghada, Egypt' },
    aiSettings: {
      bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar', 'de', 'ru'], autoOpen: false },
      voiceAgent: { enabled: true, languages: ['en', 'ar'], buttonPosition: 'bottom-right' },
      searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 8 },
    },
    seoSettings: {
      metaTitle: 'Hurghada Tours & Excursions - Book Red Sea Adventures',
      metaDescription: 'Book the best tours and excursions in Hurghada. Snorkeling, desert safaris, diving, and more.',
      keywords: ['Hurghada tours', 'Red Sea diving', 'Hurghada snorkeling', 'desert safari Hurghada'],
    },
    status: 'coming_soon',
  },
  {
    slug: 'sharm-tours',
    name: 'Sharm El Sheikh Tours',
    domain: 'sharm-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1551884170-4f149c91e9fa?w=200&h=60&fit=crop',
    tagline: 'Luxury Red Sea Experiences',
    description: 'Premium tours and experiences in Sharm El Sheikh',
    theme: { primaryColor: '#1A5490', secondaryColor: '#00B4D8', accentColor: '#FF006E' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 69 3600000', email: 'info@sharm-tours.com', address: 'Sharm El Sheikh, Egypt' },
    aiSettings: {
      bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar', 'de', 'ru'], autoOpen: false },
      voiceAgent: { enabled: true, languages: ['en', 'ar'], buttonPosition: 'bottom-right' },
      searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 8 },
    },
    seoSettings: {
      metaTitle: 'Sharm El Sheikh Tours - Book Luxury Red Sea Experiences',
      metaDescription: 'Explore Sharm El Sheikh with our premium tour packages. Diving, snorkeling, and luxury experiences.',
      keywords: ['Sharm El Sheikh tours', 'diving Sharm', 'Naama Bay experiences', 'Red Sea luxury'],
    },
    status: 'coming_soon',
  },
  {
    slug: 'cairo-tours',
    name: 'Cairo Tours & Packages',
    domain: 'cairo-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b4?w=200&h=60&fit=crop',
    tagline: 'Ancient Egypt Awaits',
    description: 'Discover the wonders of Cairo and ancient Egypt',
    theme: { primaryColor: '#8B4513', secondaryColor: '#D2691E', accentColor: '#FFD700' },
    designMode: 'luxury',
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 2 27485100', email: 'info@cairo-tours.com', address: 'Cairo, Egypt' },
    aiSettings: {
      bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar', 'de', 'ru'], autoOpen: false },
      voiceAgent: { enabled: true, languages: ['en', 'ar'], buttonPosition: 'bottom-right' },
      searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 8 },
    },
    seoSettings: {
      metaTitle: 'Cairo Tours & Packages - Book Luxury Egypt Experiences',
      metaDescription: 'Explore Cairo and the Pyramids of Giza with our luxury tour packages.',
      keywords: ['Cairo tours', 'Pyramids of Giza', 'Egyptian Museum', 'Cairo Nile cruise'],
    },
    status: 'coming_soon',
  },
  {
    slug: 'luxor-tours',
    name: 'Luxor Tours & Experiences',
    domain: 'luxor-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1563930234-c58e88bef97f?w=200&h=60&fit=crop',
    tagline: 'Ancient Thebes Revealed',
    description: 'Explore the temples and history of Luxor',
    theme: { primaryColor: '#704214', secondaryColor: '#C67C4E', accentColor: '#FFB347' },
    designMode: 'luxury',
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 95 2380425', email: 'info@luxor-tours.com', address: 'Luxor, Egypt' },
    aiSettings: {
      bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar', 'de', 'ru'], autoOpen: false },
      voiceAgent: { enabled: true, languages: ['en', 'ar'], buttonPosition: 'bottom-right' },
      searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 8 },
    },
    seoSettings: {
      metaTitle: 'Luxor Tours & Experiences - Valley of the Kings Adventures',
      metaDescription: 'Book tours to Valley of the Kings, Karnak Temple, and hot air balloon rides in Luxor.',
      keywords: ['Luxor tours', 'Valley of Kings', 'Karnak Temple', 'hot air balloon Luxor'],
    },
    status: 'coming_soon',
  },
  {
    slug: 'aswan-tours',
    name: 'Aswan Tours & Adventures',
    domain: 'aswan-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1604631868676-d6875e99f47f?w=200&h=60&fit=crop',
    tagline: 'Gateway to Nubia',
    description: 'Explore Aswan and Abu Simbel temples',
    theme: { primaryColor: '#2F4F7F', secondaryColor: '#0099CC', accentColor: '#FF6600' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 97 2301011', email: 'info@aswan-tours.com', address: 'Aswan, Egypt' },
    aiSettings: {
      bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar', 'de', 'ru'], autoOpen: false },
      voiceAgent: { enabled: true, languages: ['en', 'ar'], buttonPosition: 'bottom-right' },
      searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 8 },
    },
    seoSettings: {
      metaTitle: 'Aswan Tours & Adventures - Abu Simbel & Nile Cruises',
      metaDescription: 'Book Aswan tours including Abu Simbel temples, Nile cruises, and Nubian village visits.',
      keywords: ['Aswan tours', 'Abu Simbel', 'Nile cruise', 'Nubian culture'],
    },
    status: 'coming_soon',
  },
  {
    slug: 'dahab-tours',
    name: 'Dahab Tours & Activities',
    domain: 'dahab-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1517576443991-9c6b7c3e68b9?w=200&h=60&fit=crop',
    tagline: 'Bohemian Beach Paradise',
    description: 'Discover diving and relaxation in Dahab',
    theme: { primaryColor: '#006666', secondaryColor: '#00CCCC', accentColor: '#FF9900' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 69 3640419', email: 'info@dahab-tours.com', address: 'Dahab, Egypt' },
    aiSettings: {
      bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar', 'de', 'ru'], autoOpen: false },
      voiceAgent: { enabled: true, languages: ['en', 'ar'], buttonPosition: 'bottom-right' },
      searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 8 },
    },
    seoSettings: {
      metaTitle: 'Dahab Tours & Activities - Diving & Beach Experiences',
      metaDescription: 'Book diving, snorkeling, and beach activities in Dahab. Blue Hole diving and water sports.',
      keywords: ['Dahab diving', 'Blue Hole', 'Dahab snorkeling', 'beach relaxation Dahab'],
    },
    status: 'coming_soon',
  },
  {
    slug: 'el-gouna-tours',
    name: 'El Gouna Tours',
    domain: 'el-gouna-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=200&h=60&fit=crop',
    tagline: 'Modern Luxury Resort Paradise',
    description: 'Experience El Gouna luxury and water sports',
    theme: { primaryColor: '#1E90FF', secondaryColor: '#00CED1', accentColor: '#FFD700' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3545100', email: 'info@el-gouna-tours.com', address: 'El Gouna, Egypt' },
    aiSettings: {
      bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar', 'de', 'ru'], autoOpen: false },
      voiceAgent: { enabled: true, languages: ['en', 'ar'], buttonPosition: 'bottom-right' },
      searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 8 },
    },
    seoSettings: {
      metaTitle: 'El Gouna Tours - Water Sports & Luxury Experiences',
      metaDescription: 'Book water sports, golf, and luxury experiences in El Gouna.',
      keywords: ['El Gouna tours', 'El Gouna golf', 'Red Sea water sports', 'El Gouna windsurfing'],
    },
    status: 'coming_soon',
  },
  {
    slug: 'makadi-bay-tours',
    name: 'Makadi Bay Tours',
    domain: 'makadi-bay-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1514282401047-430e6570acda?w=200&h=60&fit=crop',
    tagline: 'Exclusive Beach Escape',
    description: 'Exclusive tours and activities in Makadi Bay',
    theme: { primaryColor: '#0055AA', secondaryColor: '#00DDFF', accentColor: '#FF5500' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3701100', email: 'info@makadi-bay-tours.com', address: 'Makadi Bay, Egypt' },
    aiSettings: {
      bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar', 'de', 'ru'], autoOpen: false },
      voiceAgent: { enabled: true, languages: ['en', 'ar'], buttonPosition: 'bottom-right' },
      searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 8 },
    },
    seoSettings: {
      metaTitle: 'Makadi Bay Tours - Exclusive Resort & Water Activities',
      metaDescription: 'Discover Makadi Bay tours including desert safaris, snorkeling, and water sports.',
      keywords: ['Makadi Bay tours', 'Makadi Bay snorkeling', 'desert safari Makadi', 'Makadi beach'],
    },
    status: 'coming_soon',
  },
  {
    slug: 'marsa-alam-tours',
    name: 'Marsa Alam Tours',
    domain: 'marsa-alam-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1583109282925-404b7691c545?w=200&h=60&fit=crop',
    tagline: 'Pristine Diving Destination',
    description: 'Explore pristine diving and marine life in Marsa Alam',
    theme: { primaryColor: '#1A3A52', secondaryColor: '#2E8B9E', accentColor: '#FF8C42' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3930025', email: 'info@marsa-alam-tours.com', address: 'Marsa Alam, Egypt' },
    aiSettings: {
      bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar', 'de', 'ru'], autoOpen: false },
      voiceAgent: { enabled: true, languages: ['en', 'ar'], buttonPosition: 'bottom-right' },
      searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 8 },
    },
    seoSettings: {
      metaTitle: 'Marsa Alam Tours - Pristine Diving & Marine Life',
      metaDescription: 'Book diving, snorkeling, and marine encounters in Marsa Alam. Dolphin and turtle encounters.',
      keywords: ['Marsa Alam diving', 'dolphin encounters', 'Marsa Alam snorkeling', 'marine life tours'],
    },
    status: 'coming_soon',
  },
  {
    slug: 'red-sea-tours',
    name: 'Red Sea Tours & Adventures',
    domain: 'red-sea-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=200&h=60&fit=crop',
    tagline: 'Complete Red Sea Exploration',
    description: 'Comprehensive tours across the Red Sea coast',
    theme: { primaryColor: '#CC0000', secondaryColor: '#FF6666', accentColor: '#0099CC' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3500000', email: 'info@red-sea-tours.com', address: 'Red Sea, Egypt' },
    aiSettings: {
      bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar', 'de', 'ru'], autoOpen: false },
      voiceAgent: { enabled: true, languages: ['en', 'ar'], buttonPosition: 'bottom-right' },
      searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 8 },
    },
    seoSettings: {
      metaTitle: 'Red Sea Tours & Adventures - Diving, Snorkeling & Water Sports',
      metaDescription: 'Explore the Red Sea coast with our comprehensive tour packages. Diving, snorkeling, water sports.',
      keywords: ['Red Sea tours', 'Red Sea diving', 'Red Sea snorkeling', 'water sports Red Sea'],
    },
    status: 'coming_soon',
  },
  {
    slug: 'soma-bay-tours',
    name: 'Soma Bay Tours',
    domain: 'soma-bay-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=200&h=60&fit=crop',
    tagline: 'Wind & Water Paradise',
    description: 'Water sports and relaxation in Soma Bay',
    theme: { primaryColor: '#0066FF', secondaryColor: '#00FFFF', accentColor: '#FF6600' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3754000', email: 'info@soma-bay-tours.com', address: 'Soma Bay, Egypt' },
    aiSettings: {
      bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar', 'de', 'ru'], autoOpen: false },
      voiceAgent: { enabled: true, languages: ['en', 'ar'], buttonPosition: 'bottom-right' },
      searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 8 },
    },
    seoSettings: {
      metaTitle: 'Soma Bay Tours - Windsurfing & Kitesurfing',
      metaDescription: 'Book windsurfing, kitesurfing, and beach activities in Soma Bay.',
      keywords: ['Soma Bay windsurfing', 'kitesurfing Soma', 'Soma Bay water sports', 'beach relaxation'],
    },
    status: 'coming_soon',
  },
  {
    slug: 'taba-tours',
    name: 'Taba Tours & Excursions',
    domain: 'taba-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=200&h=60&fit=crop',
    tagline: 'Mountain & Sea Adventure',
    description: 'Adventure tours in scenic Taba',
    theme: { primaryColor: '#4A4A4A', secondaryColor: '#FF8C00', accentColor: '#00CCFF' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 69 3530022', email: 'info@taba-tours.com', address: 'Taba, Egypt' },
    aiSettings: {
      bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar', 'de', 'ru'], autoOpen: false },
      voiceAgent: { enabled: true, languages: ['en', 'ar'], buttonPosition: 'bottom-right' },
      searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 8 },
    },
    seoSettings: {
      metaTitle: 'Taba Tours & Excursions - Mountain Hiking & Diving',
      metaDescription: 'Book mountain hikes, diving, and adventure tours in Taba.',
      keywords: ['Taba tours', 'Taba hiking', 'Taba diving', 'mountain adventures Taba'],
    },
    status: 'coming_soon',
  },
  {
    slug: 'egypt-tours',
    name: 'Egypt Tours Network',
    domain: 'egypt-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b4?w=200&h=60&fit=crop',
    tagline: 'Experience the Land of Pharaohs',
    description: 'National network of Egypt tours and experiences across all destinations',
    theme: { primaryColor: '#8B4513', secondaryColor: '#D2B48C', accentColor: '#FFD700' },
    designMode: 'luxury',
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 2 27000000', email: 'info@egypt-tours.com', address: 'Cairo, Egypt' },
    aiSettings: {
      bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar', 'de', 'ru'], autoOpen: false },
      voiceAgent: { enabled: true, languages: ['en', 'ar'], buttonPosition: 'bottom-right' },
      searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 8 },
    },
    seoSettings: {
      metaTitle: 'Egypt Tours Network - Luxury Tours & Experiences Nationwide',
      metaDescription: 'Book comprehensive Egypt tour packages including Pyramids, temples, Nile cruises, and Red Sea diving.',
      keywords: ['Egypt tours', 'Egypt vacation packages', 'Nile cruise Egypt', 'ancient Egypt tours', 'Red Sea Egypt'],
    },
    status: 'coming_soon',
  },
  // ─── Attraction-based Tenants (each attraction is also its own tenant site) ───
  {
    slug: 'cairo-night-cruise',
    name: 'Cairo Night Cruise',
    domain: 'cairo-night-cruise.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1568322503592-e8a7c8e29e75?w=200&h=60&fit=crop',
    tagline: 'Magical Nile Evenings',
    description: 'Luxury dinner cruise on the Nile through Cairo with live entertainment and gourmet dining',
    theme: { primaryColor: '#1A1A2E', secondaryColor: '#D4AF37', accentColor: '#E94560' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 2 27485100', email: 'info@cairo-night-cruise.com', address: 'Cairo, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Cairo Night Cruise - Nile Dinner Cruise with Entertainment', metaDescription: 'Book a magical Nile dinner cruise in Cairo with live music, belly dancing, and gourmet dining.', keywords: ['Cairo Nile cruise', 'dinner cruise Cairo', 'Nile cruise night'] },
    status: 'coming_soon',
  },
  {
    slug: 'cairo-tour-from-hurghada',
    name: 'Cairo Tour from Hurghada',
    domain: 'cairo-tour-from-hurghada.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b4?w=200&h=60&fit=crop',
    tagline: 'Pyramids in a Day',
    description: 'Full-day Cairo excursion from Hurghada including Pyramids, Sphinx, and Egyptian Museum',
    theme: { primaryColor: '#8B6914', secondaryColor: '#C9A962', accentColor: '#2B5F9E' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@cairo-tour-hurghada.com', address: 'Hurghada, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Cairo Tour from Hurghada - Pyramids Day Trip', metaDescription: 'Book a full-day Cairo tour from Hurghada by air. Visit Pyramids, Sphinx and Egyptian Museum.', keywords: ['Cairo from Hurghada', 'Pyramids day trip', 'Hurghada to Cairo'] },
    status: 'coming_soon',
  },
  {
    slug: 'cairo-tours-packages',
    name: 'Cairo Tours Packages',
    domain: 'cairo-tours-packages.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=200&h=60&fit=crop',
    tagline: 'Complete Cairo Experience',
    description: 'Multi-day Cairo tour packages covering Pyramids, museums, markets, and Nile experiences',
    theme: { primaryColor: '#704214', secondaryColor: '#B8860B', accentColor: '#1E3A8A' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 2 27485100', email: 'info@cairo-tours-packages.com', address: 'Cairo, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Cairo Tours Packages - Multi-Day Egypt Experiences', metaDescription: 'Book complete Cairo tour packages. Pyramids, museums, Nile cruises, and more.', keywords: ['Cairo tour packages', 'Egypt packages', 'multi-day Cairo'] },
    status: 'coming_soon',
  },
  {
    slug: 'camel-riding-hurghada',
    name: 'Camel Riding Hurghada',
    domain: 'camel-riding-hurghada.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1549388604-817d15aa0110?w=200&h=60&fit=crop',
    tagline: 'Desert Camel Adventures',
    description: 'Authentic camel riding experiences in the Hurghada desert with Bedouin hospitality',
    theme: { primaryColor: '#C2956B', secondaryColor: '#E8C99B', accentColor: '#5C3D2E' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@camel-riding-hurghada.com', address: 'Hurghada, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Camel Riding Hurghada - Desert Adventures', metaDescription: 'Book camel riding in Hurghada desert. Sunset rides and Bedouin experiences.', keywords: ['camel riding Hurghada', 'desert camel', 'Hurghada desert tour'] },
    status: 'coming_soon',
  },
  {
    slug: 'giftun-island-hurghada',
    name: 'Giftun Island Hurghada',
    domain: 'giftun-island-hurghada.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=200&h=60&fit=crop',
    tagline: 'Paradise Island Escape',
    description: 'Snorkeling and beach day trips to Giftun Island from Hurghada',
    theme: { primaryColor: '#006994', secondaryColor: '#40E0D0', accentColor: '#FF7F50' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@giftun-island.com', address: 'Hurghada, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Giftun Island Hurghada - Snorkeling & Beach Trips', metaDescription: 'Book Giftun Island day trips from Hurghada. Snorkeling, swimming, and beach fun.', keywords: ['Giftun Island', 'Hurghada island trip', 'snorkeling Giftun'] },
    status: 'coming_soon',
  },
  {
    slug: 'horse-riding-hurghada',
    name: 'Horse Riding Hurghada',
    domain: 'horse-riding-hurghada.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=200&h=60&fit=crop',
    tagline: 'Beach & Desert Horseback Riding',
    description: 'Scenic horseback riding along Hurghada beaches and through the desert',
    theme: { primaryColor: '#5C4033', secondaryColor: '#8B6C5C', accentColor: '#DAA520' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@horse-riding-hurghada.com', address: 'Hurghada, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Horse Riding Hurghada - Beach & Desert Rides', metaDescription: 'Book horse riding on Hurghada beaches and desert trails.', keywords: ['horse riding Hurghada', 'beach horse ride', 'Hurghada equestrian'] },
    status: 'coming_soon',
  },
  {
    slug: 'hurghada-fishing',
    name: 'Hurghada Fishing',
    domain: 'hurghada-fishing.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1544551763-92ab472cad1d?w=200&h=60&fit=crop',
    tagline: 'Red Sea Deep Sea Fishing',
    description: 'Deep sea fishing charters in Hurghada with professional crew and equipment',
    theme: { primaryColor: '#003366', secondaryColor: '#336699', accentColor: '#FF6633' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@hurghada-fishing.com', address: 'Hurghada Marina, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Hurghada Deep Sea Fishing - Red Sea Charters', metaDescription: 'Book deep sea fishing charters in Hurghada. Catch big fish in the Red Sea.', keywords: ['Hurghada fishing', 'deep sea fishing', 'Red Sea fishing charter'] },
    status: 'coming_soon',
  },
  {
    slug: 'hurghada-jeep-safari',
    name: 'Hurghada Jeep Safari',
    domain: 'hurghada-jeep-safari.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1517636317280-b95c2a37c708?w=200&h=60&fit=crop',
    tagline: 'Desert Off-Road Thrills',
    description: 'Thrilling off-road jeep safari through the Hurghada desert',
    theme: { primaryColor: '#8B4513', secondaryColor: '#CD853F', accentColor: '#DC143C' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@hurghada-jeep-safari.com', address: 'Hurghada, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Hurghada Jeep Safari - Desert Off-Road Adventure', metaDescription: 'Book thrilling jeep desert safari in Hurghada. Dune bashing and Bedouin camp.', keywords: ['Hurghada jeep safari', 'desert safari', 'dune bashing Hurghada'] },
    status: 'coming_soon',
  },
  {
    slug: 'hurghada-luxury-cruise',
    name: 'Hurghada Luxury Cruise',
    domain: 'hurghada-luxury-cruise.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=200&h=60&fit=crop',
    tagline: 'Premium Red Sea Yachting',
    description: 'Luxury yacht cruises along the Red Sea from Hurghada with fine dining',
    theme: { primaryColor: '#0A0A0F', secondaryColor: '#D4AF37', accentColor: '#FFFFFF' },
    designMode: 'luxury',
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@hurghada-luxury-cruise.com', address: 'Hurghada Marina, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Hurghada Luxury Yacht Cruise - Premium Red Sea Experience', metaDescription: 'Book luxury yacht cruise in Hurghada. Fine dining, snorkeling, and island hopping.', keywords: ['Hurghada luxury cruise', 'yacht Hurghada', 'Red Sea yacht'] },
    status: 'coming_soon',
  },
  {
    slug: 'hurghada-private-safari',
    name: 'Hurghada Private Safari',
    domain: 'hurghada-private-safari.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=200&h=60&fit=crop',
    tagline: 'Exclusive Desert Experiences',
    description: 'Private VIP desert safari tours from Hurghada with exclusive Bedouin camp',
    theme: { primaryColor: '#704214', secondaryColor: '#C67C4E', accentColor: '#E63946' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@hurghada-private-safari.com', address: 'Hurghada, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Hurghada Private Safari - VIP Desert Experience', metaDescription: 'Book private desert safari from Hurghada. VIP Bedouin camp and exclusive tours.', keywords: ['Hurghada private safari', 'VIP desert tour', 'exclusive safari Hurghada'] },
    status: 'coming_soon',
  },
  {
    slug: 'hurghada-private-tours',
    name: 'Hurghada Private Tours',
    domain: 'hurghada-private-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=200&h=60&fit=crop',
    tagline: 'Personalized City Experiences',
    description: 'Private guided tours of Hurghada with local insights and personalized itineraries',
    theme: { primaryColor: '#2C5F2D', secondaryColor: '#97BC62', accentColor: '#FFB74D' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@hurghada-private-tours.com', address: 'Hurghada, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Hurghada Private Tours - Guided City Experiences', metaDescription: 'Book private guided tours in Hurghada. Custom itineraries with local guides.', keywords: ['Hurghada private tours', 'guided tour Hurghada', 'city tour Hurghada'] },
    status: 'coming_soon',
  },
  {
    slug: 'hurghada-snorkeling',
    name: 'Hurghada Snorkeling',
    domain: 'hurghada-snorkeling.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=200&h=60&fit=crop',
    tagline: 'Red Sea Coral Reef Adventures',
    description: 'World-class snorkeling trips to coral reefs and marine reserves around Hurghada',
    theme: { primaryColor: '#006B7D', secondaryColor: '#48D1CC', accentColor: '#FF6B35' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@hurghada-snorkeling.com', address: 'Hurghada Marina, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Hurghada Snorkeling - Red Sea Coral Reef Trips', metaDescription: 'Book snorkeling trips in Hurghada. Explore stunning coral reefs and marine life.', keywords: ['Hurghada snorkeling', 'Red Sea snorkeling', 'coral reef Hurghada'] },
    status: 'coming_soon',
  },
  {
    slug: 'hurghada-spa',
    name: 'Hurghada Spa',
    domain: 'hurghada-spa.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1540555700478-4be289fbec6e?w=200&h=60&fit=crop',
    tagline: 'Luxury Wellness & Relaxation',
    description: 'Premium spa treatments and wellness experiences at luxury Hurghada resorts',
    theme: { primaryColor: '#5D4E60', secondaryColor: '#C4A7C7', accentColor: '#F0E6CC' },
    designMode: 'luxury',
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@hurghada-spa.com', address: 'Hurghada, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Hurghada Spa - Luxury Wellness & Relaxation', metaDescription: 'Book spa treatments in Hurghada luxury resorts. Massages, facials, and wellness packages.', keywords: ['Hurghada spa', 'luxury spa Egypt', 'wellness Hurghada'] },
    status: 'coming_soon',
  },
  {
    slug: 'luxor-air-balloon',
    name: 'Luxor Air Balloon',
    domain: 'luxor-air-balloon.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?w=200&h=60&fit=crop',
    tagline: 'Sunrise over Ancient Temples',
    description: 'Breathtaking hot air balloon flights over the Valley of the Kings at sunrise',
    theme: { primaryColor: '#E07C24', secondaryColor: '#FFCC00', accentColor: '#2E86AB' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 95 2380425', email: 'info@luxor-air-balloon.com', address: 'Luxor, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Luxor Hot Air Balloon - Sunrise Flight over Temples', metaDescription: 'Book hot air balloon ride in Luxor. Sunrise views over Valley of the Kings.', keywords: ['Luxor balloon', 'hot air balloon Luxor', 'sunrise balloon ride'] },
    status: 'coming_soon',
  },
  {
    slug: 'luxor-tour-from-hurghada',
    name: 'Luxor Tour from Hurghada',
    domain: 'luxor-tour-from-hurghada.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1563930234-c58e88bef97f?w=200&h=60&fit=crop',
    tagline: 'Ancient Temples Day Trip',
    description: 'Full-day tour to Luxor from Hurghada visiting temples and the Valley of the Kings',
    theme: { primaryColor: '#704214', secondaryColor: '#C67C4E', accentColor: '#1A5276' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@luxor-from-hurghada.com', address: 'Hurghada, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Luxor Tour from Hurghada - Valley of the Kings Day Trip', metaDescription: 'Book Luxor day tour from Hurghada. Visit Valley of the Kings, Karnak Temple.', keywords: ['Luxor from Hurghada', 'Luxor day trip', 'Valley of Kings tour'] },
    status: 'coming_soon',
  },
  {
    slug: 'makadi-bay-safari',
    name: 'Makadi Bay Safari',
    domain: 'makadi-bay-safari.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1517636317280-b95c2a37c708?w=200&h=60&fit=crop',
    tagline: 'Resort Desert Adventures',
    description: 'Desert safari excursions from Makadi Bay resorts',
    theme: { primaryColor: '#A0522D', secondaryColor: '#DEB887', accentColor: '#DC143C' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3701100', email: 'info@makadi-bay-safari.com', address: 'Makadi Bay, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Makadi Bay Desert Safari - Resort Excursions', metaDescription: 'Book desert safari from Makadi Bay. Quad biking, camel rides, and Bedouin dinner.', keywords: ['Makadi Bay safari', 'desert safari Makadi', 'quad biking Makadi Bay'] },
    status: 'coming_soon',
  },
  {
    slug: 'makadi-bay-snorkeling',
    name: 'Makadi Bay Snorkeling',
    domain: 'makadi-bay-snorkeling.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=200&h=60&fit=crop',
    tagline: 'Crystal Clear Reef Adventures',
    description: 'Half-day snorkeling excursions to pristine reefs from Makadi Bay',
    theme: { primaryColor: '#007BA7', secondaryColor: '#00CED1', accentColor: '#FF6347' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3701100', email: 'info@makadi-bay-snorkeling.com', address: 'Makadi Bay, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Makadi Bay Snorkeling - Reef Excursions', metaDescription: 'Book snorkeling trips from Makadi Bay. Pristine coral reefs and tropical fish.', keywords: ['Makadi Bay snorkeling', 'reef tour Makadi', 'snorkeling Red Sea'] },
    status: 'coming_soon',
  },
  {
    slug: 'orange-bay-tours',
    name: 'Orange Bay Tours',
    domain: 'orange-bay-tours.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=200&h=60&fit=crop',
    tagline: 'Turquoise Paradise Island',
    description: 'Island hopping and beach day trips to Orange Bay from Hurghada',
    theme: { primaryColor: '#FF8C00', secondaryColor: '#00CED1', accentColor: '#FFFFFF' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@orange-bay-tours.com', address: 'Hurghada Marina, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Orange Bay Tours - Island Day Trips from Hurghada', metaDescription: 'Book Orange Bay island trips from Hurghada. Swimming, snorkeling, and beach relaxation.', keywords: ['Orange Bay Hurghada', 'island tour Hurghada', 'Orange Bay trip'] },
    status: 'coming_soon',
  },
  {
    slug: 'parasailing-hurghada',
    name: 'Parasailing Hurghada',
    domain: 'parasailing-hurghada.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=200&h=60&fit=crop',
    tagline: 'Fly Over the Red Sea',
    description: 'Thrilling parasailing adventures over the Red Sea in Hurghada',
    theme: { primaryColor: '#0077B6', secondaryColor: '#00B4D8', accentColor: '#FF006E' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@parasailing-hurghada.com', address: 'Hurghada Beach, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Parasailing Hurghada - Fly Over the Red Sea', metaDescription: 'Book parasailing in Hurghada. Soar above the Red Sea for incredible aerial views.', keywords: ['parasailing Hurghada', 'Red Sea parasailing', 'water sports Hurghada'] },
    status: 'coming_soon',
  },
  {
    slug: 'pyramids-excursions',
    name: 'Pyramids Excursions',
    domain: 'pyramids-excursions.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b4?w=200&h=60&fit=crop',
    tagline: 'Walk with the Pharaohs',
    description: 'Guided excursions to the Pyramids of Giza, Sphinx, and surrounding sites',
    theme: { primaryColor: '#8B6914', secondaryColor: '#DAA520', accentColor: '#1E3A5F' },
    designMode: 'luxury',
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 2 27485100', email: 'info@pyramids-excursions.com', address: 'Giza, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Pyramids Excursions - Guided Tours of Giza', metaDescription: 'Book guided excursions to the Pyramids of Giza and the Great Sphinx.', keywords: ['Pyramids tour', 'Giza Pyramids', 'Sphinx tour', 'Egypt excursions'] },
    status: 'coming_soon',
  },
  {
    slug: 'sharm-dinner-cruise',
    name: 'Sharm Dinner Cruise',
    domain: 'sharm-dinner-cruise.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1568322503592-e8a7c8e29e75?w=200&h=60&fit=crop',
    tagline: 'Evening on the Red Sea',
    description: 'Luxury dinner cruise in Sharm El Sheikh with live entertainment and stunning views',
    theme: { primaryColor: '#1A1A2E', secondaryColor: '#C0392B', accentColor: '#F1C40F' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 69 3600000', email: 'info@sharm-dinner-cruise.com', address: 'Naama Bay, Sharm El Sheikh, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Sharm Dinner Cruise - Evening Red Sea Cruise', metaDescription: 'Book dinner cruise in Sharm El Sheikh. Live music, dining, and sea views.', keywords: ['Sharm dinner cruise', 'Sharm El Sheikh cruise', 'dinner cruise Red Sea'] },
    status: 'coming_soon',
  },
  {
    slug: 'toureg-safari',
    name: 'Toureg Safari',
    domain: 'toureg-safari.foxesnetwork.com',
    logo: 'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=200&h=60&fit=crop',
    tagline: 'Authentic Bedouin Desert Experience',
    description: 'Traditional Touareg-style desert safari with cultural immersion and stargazing',
    theme: { primaryColor: '#5D4037', secondaryColor: '#A1887F', accentColor: '#FF5722' },
    defaultCurrency: 'EGP',
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'de', 'ru'],
    timezone: 'Africa/Cairo',
    contactInfo: { phone: '+20 65 3468000', email: 'info@toureg-safari.com', address: 'Hurghada, Egypt' },
    aiSettings: { bookingWidget: { enabled: true, position: 'bottom-right', languages: ['en', 'ar'], autoOpen: false }, voiceAgent: { enabled: false, languages: ['en', 'ar'], buttonPosition: 'bottom-right' }, searchWidget: { enabled: true, showPopularSearches: true, maxSuggestions: 6 } },
    seoSettings: { metaTitle: 'Toureg Safari - Authentic Desert Cultural Experience', metaDescription: 'Book Touareg desert safari. Bedouin cultural immersion, dinner, and stargazing.', keywords: ['Touareg safari', 'Bedouin experience', 'desert cultural tour'] },
    status: 'coming_soon',
  },
];

const users = [
  {
    email: 'admin@attractions-network.com',
    password: 'Admin@123456',
    firstName: 'Super',
    lastName: 'Admin',
    role: 'super-admin',
    status: 'active',
  },
  {
    email: 'customer@example.com',
    password: 'Customer@123',
    firstName: 'John',
    lastName: 'Doe',
    role: 'customer',
    status: 'active',
    country: 'United States',
  },
];

const seed = async (): Promise<void> => {
  try {
    console.log('🌱 Starting database seed...\n');

    await connectDatabase();

    // Clear existing data
    console.log('🗑️  Clearing existing data...');
    await Promise.all([
      User.deleteMany({}),
      Tenant.deleteMany({}),
      Attraction.deleteMany({}),
      Category.deleteMany({}),
      Destination.deleteMany({}),
      Review.deleteMany({}),
      Booking.deleteMany({}),
    ]);

    // Seed categories
    console.log('📁 Seeding categories...');
    await Category.insertMany(categories);
    console.log(`   ✅ ${categories.length} categories created`);

    // Seed destinations
    console.log('🌍 Seeding destinations...');
    await Destination.insertMany(destinations);
    console.log(`   ✅ ${destinations.length} destinations created`);

    // Seed tenants
    console.log('🏢 Seeding tenants...');
    const createdTenants = await Tenant.insertMany(tenants);
    console.log(`   ✅ ${tenants.length} tenants created`);

    // Seed attractions with tenant associations
    console.log('🎢 Seeding attractions...');
    const attractionsWithTenants = attractions.map((a) => {
      const tenantIds = createdTenants.filter((t) => {
        const slug = t.slug;
        // 1. Direct slug match: attraction-based tenant matches its own attraction
        if (slug === a.slug) return true;
        // 2. Link by destination city (destination + attraction tenants)
        const city = a.destination.city.toLowerCase().replace(/\s+/g, '-');
        if (slug.includes(city)) return true;
        // Special case: Sharm El Sheikh → 'sharm'
        if (a.destination.city === 'Sharm El Sheikh' && slug.includes('sharm')) return true;
        // 3. Also link to national umbrella and Red Sea regional tenant
        if (slug === 'egypt-tours') return true;
        if (slug === 'red-sea-tours') return true;
        return false;
      }).map((t) => t._id);

      return {
        ...a,
        tenantIds,
      };
    });

    await Attraction.insertMany(attractionsWithTenants);
    console.log(`   ✅ ${attractions.length} attractions created`);

    // Seed users (password will be hashed by pre-save hook)
    console.log('👥 Seeding users...');
    for (const userData of users) {
      await User.create({
        ...userData,
        assignedTenants: userData.role === 'super-admin' ? createdTenants.map((t) => t._id) : [],
      });
    }
    console.log(`   ✅ ${users.length} users created`);

    console.log('\n✅ Database seeded successfully!\n');
    console.log('📝 Test accounts:');
    console.log('   Admin: admin@attractions-network.com / Admin@123456');
    console.log('   Customer: customer@example.com / Customer@123');
    console.log('\n📊 Egypt Network Summary:');
    console.log('   ✅ 13 Destination Tenants (coming_soon)');
    console.log('   ✅ 22 Attraction Tenants (coming_soon)');
    console.log('   ✅ 35 Total Egypt Tenants');
    console.log('   ✅ 13 Egypt Destinations');
    console.log('   ✅ 22 Egypt Attractions');

    await disconnectDatabase();
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  }
};

seed();
